services:
  llm:
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - CHROMA_URL=http://host.docker.internal:8002
    depends_on: []  # Disable auto spin up
  ollama:
    deploy:
      scale: 0   # Disable container
  chromadb:
    deploy:
      scale: 0   # Disable container
